quarkus:

  http:
    cors: 
      ~: true    

  datasource:
    db-kind: mysql
    db-version: 8.4

  hibernate-orm:
    database:
      generation: none

  flyway:
    migrate-at-start: true
    baseline-on-migrate: true

  banner:
    path: banner.txt

  container-image:
    builder: jib
    build: true
    push: true
    registry: degas.bruun-rasmussen.dk:5000
